Первая редакция
Anton-Pevitsyn/goit-markup-hw-03 pull request #1
Opened 2021-01-03 21:39 UTC by Anton-Pevitsyn

2021-01-04 11:27 UTC, magom001 requested changes
Посмотри на картинку в карточках на странице портфолио

2021-01-04 11:27 UTC, magom001 commented on css/style.css
> +  color: #000000;
цвет не в переменной

2021-01-04 11:27 UTC, magom001 commented on css/style.css
> +  color: #000000;
цвет не в переменной

2021-01-04 11:27 UTC, magom001 commented on css/style.css
> +  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.12), 0px 1px 1px rgba(0, 0, 0, 0.14),
это в фигме такой бред написан?

2021-01-04 11:27 UTC, magom001 commented on css/style.css
> +.portfolio-card:nth-last-child(-n + 3) {
всем уже написал, напишу и тебе: что будет с версткой, если карточек станет не 9, а 8 или 7?

2021-01-04 11:27 UTC, magom001 commented on css/style.css
> +  color: var(--main-title-color);
на макетах есть тень

2021-01-04 11:27 UTC, magom001 commented on css/style.css
> +  display: block;
картинка выступает за край карточки

2021-01-04 13:13 UTC, Anton-Pevitsyn commented on css/style.css
> +  box-shadow: 0px 1px 3px rgba(0, 0, 0, 0.12), 0px 1px 1px rgba(0, 0, 0, 0.14),
Да, скопировал из макета

2021-01-04 13:29 UTC, Anton-Pevitsyn commented on css/style.css
> +  display: block;
Картинка не выступает, у нее падинги и маржины нулевые 
наверно это
  border: 1px solid #eeeeee;
опять же из макета, не сам придумал.

2021-01-04 14:33 UTC, magom001 commented on css/style.css
> +  display: block;
Ты заставил меня открыть макет в фигме. Там картинка не выступает. Border там по-другому сделан. См. макет.

2021-01-05 13:14 UTC, Anton-Pevitsyn commented on css/style.css
> +  display: block;
Разобрался, исправил. В макете немного описано кривовато, нарисовано правильно, а вот свойство border: 1px solid #eeeeee; указано у всей li.

2021-01-05 13:22 UTC, Anton-Pevitsyn commented on css/style.css
> +  color: var(--main-title-color);
Исправил

2021-01-05 13:22 UTC, Anton-Pevitsyn commented on css/style.css
> +  color: #000000;
исправил

2021-01-05 13:22 UTC, Anton-Pevitsyn commented on css/style.css
> +  color: #000000;
Исправил

2021-01-05 13:28 UTC, Anton-Pevitsyn commented on css/style.css
> +.portfolio-card:nth-last-child(-n + 3) {
Ничего не случится, до того как h2 и p не были обернуты в div у первого из последних 3х который переносился на 2ю строку выпадало 10px откуда-то, но после того как я обернул h2 и p в div проблема ушла, это свойство будет работать сколько бы карточек не было, сломается если только изменится количество карточек в строку. 
На следующей практике, объясни откуда 10px выпадают у li  я так и не разобрался.

2021-01-05 18:02 UTC, Anton-Pevitsyn commented on css/style.css
> +  display: block;
Еще раз разобрался, div это все фигня, родительскому ul задал свойство align-items: flex-start;

2021-01-05 19:00 UTC, magom001 approved these changes
небольшие замечания

2021-01-05 19:00 UTC, magom001 commented on css/style.css
> +  border: 1px solid #eeeeee;
цвет все еще не в переменной

2021-01-05 19:00 UTC, magom001 commented on css/style.css
>    color: rgba(255, 255, 255, 0.6);
цвет унеси в переменную

2021-01-06 11:01 UTC, merged